presubmits:
  kubernetes/test-infra:
  - name: pull-test-infra-bazel
    branches:
    - master
    always_run: true
    decorate: true
    labels:
      preset-service-account: "true"
      preset-bazel-scratch-dir: "true"
    spec:
      containers:
      - image: gcr.io/k8s-testimages/launcher.gcr.io/google/bazel:2.2.0-from-2.0.0
        command:
        - hack/bazel.sh
        args:
        - test
        - --config=ci
        - --nobuild_tests_only
        - //...
    annotations:
      testgrid-dashboards: presubmits-test-infra
      testgrid-tab-name: bazel

  - name: pull-test-infra-gubernator
    branches:
    - master
    run_if_changed: 'gubernator|config/prow/config.yaml'
    decorate: true
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: gcr.io/k8s-testimages/gubernator:v20200520-098b536
        command:
        - ./gubernator/test-gubernator.sh
        env:
        - name: WORKSPACE
          value: "/workspace"
    annotations:
      testgrid-dashboards: presubmits-test-infra
      testgrid-tab-name: gubernator

  - name: pull-test-infra-verify-file-perms
    branches:
    - master
    always_run: true
    decorate: true
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20200521-100609e-experimental
        command:
        - ./hack/verify-file-perms.sh
    annotations:
      testgrid-dashboards: presubmits-test-infra
      testgrid-tab-name: verify-file-perms

  - name: pull-test-infra-yamllint
    always_run: true
    decorate: true
    spec:
      containers:
      - image: quay.io/kubermatic/yamllint:0.1
        command:
        - yamllint
        - -c
        - config/jobs/.yamllint.conf
        - config/jobs
        - config/prow/cluster
    annotations:
      testgrid-dashboards: presubmits-test-infra
      testgrid-tab-name: verify-yaml

  - name: pull-test-infra-prow-checkconfig
    decorate: true
    run_if_changed: '^(config/prow/(config|plugins).yaml$|config/jobs/.*.yaml$)'
    spec:
      containers:
      - image: gcr.io/k8s-prow/checkconfig:v20200522-5ebaf9c52
        command:
        - /checkconfig
        args:
        - --config-path=config/prow/config.yaml
        - --job-config-path=config/jobs
        - --plugin-config=config/prow/plugins.yaml
        - --strict
        - --warnings=mismatched-tide-lenient
        - --warnings=tide-strict-branch
        - --warnings=needs-ok-to-test
        - --warnings=validate-owners
        - --warnings=missing-trigger
        - --warnings=validate-urls
        - --warnings=unknown-fields
    annotations:
      testgrid-dashboards: presubmits-test-infra
